package com.example.mvvm_codinginflow_25feb;

//1ST STEP

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;

@Entity(tableName = "note_table") //name of our table

public class Note {

    //after creating these fields, room will automatically generate column for these fields,\

    @PrimaryKey(autoGenerate = true) //uniquely identify each entry / row

    private int id;

    private String title;
    private String description;


    private int priority;



    public Note(String title, String description, int priority) {
        this.title = title;
        this.description = description;
        this.priority = priority;
    }

    //id is autogenerated but needed start value.
    //cant put in constructor since will be used again and again.
    public void setId(){
        this.id=id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getPriority() {
        return priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }
}
